stages:
  - build
  - deploy

build:
  stage: build
  image: docker:24.0.5
  services:
    - docker:24.0.5-dind
  script:
    - docker-compose build
    - tar -czvf app.tar.gz * .[^.]*
  artifacts:
    paths:
      - app.tar.gz
    expire_in: 1 hour
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'

deploy:
  stage: deploy
  image: alpine:latest
  before_script:
    - apk add --no-cache openssh-client tar gzip docker-cli
  script:
    - mkdir -p ~/.ssh
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - ssh-keyscan -p $SSH_PORT $SSH_HOST >> ~/.ssh/known_hosts
    - scp -P $SSH_PORT app.tar.gz $SSH_USER@$SSH_HOST:/tmp/app.tar.gz
    - ssh -p $SSH_PORT $SSH_USER@$SSH_HOST "
      mkdir -p /tmp/hiperdocs &&
      tar -xzvf /tmp/app.tar.gz -C /tmp/hiperdocs &&
      cd /tmp/hiperdocs &&
      docker compose down || true &&
      docker compose up -d
      "
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
