stages:
  - build
  - deploy

variables:
  DOCKER_IMAGE: "hiperdocs:latest"

stages:
  - build
  - deploy

variables:
  DOCKER_IMAGE: "$SSH_HOST/your-project-name:latest"

# Build Docker image
build:
  stage: build
  image: docker:24.0.5
  services:
    - docker:24.0.5-dind
  script:
    - docker build -t $DOCKER_IMAGE .
    - docker save $DOCKER_IMAGE > image.tar
  artifacts:
    paths:
      - image.tar
    expire_in: 1 hour
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'

# Deploy to server
deploy:
  stage: deploy
  image: alpine:latest
  before_script:
    - apk add --no-cache openssh-client docker-cli
  script:
    - mkdir -p ~/.ssh
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - ssh-keyscan -p $SSH_PORT $SSH_HOST >> ~/.ssh/known_hosts
    - scp -P $SSH_PORT image.tar $SSH_USER@$SSH_HOST:/tmp/image.tar
    - ssh -p $SSH_PORT $SSH_USER@$SSH_HOST "
        docker load -i /tmp/image.tar &&
        docker stop app || true &&
        docker rm app || true &&
        docker run -d --name app -p 3000:3000 $DOCKER_IMAGE
      "
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'

